### ISSUE TITLE
Mangas imported from fakkudroid v2 use obsolete data.json file resulting in an impermanent timestamp.

### ISSUE THREAD

**Issue by neosubmarino** [csaki/Hentoid#11]
Any manga imported from fakkudroid v2 gets their timestamp set to when it was imported. This information is kept in appdata so reinstalling the app will mean this information is lost and reset again. Because of this, after importing, mangas from v2 would always stay on top when the downloads list is "ordered by date"

Affects version:
All Hentoid & Fakkudroid v3

**Comment by neosubmarino** [comment]
I think it's best to fix this along with the &amp; bug by adding a new option in preferences because if the fix was applied to the import process, it wouldn't fix the already imported mangas.

Reference:
http://fakkudroid.blogspot.com/2015/07/hentoid-v103.html?showComment=1436130760803&m=1#c7177407717869509267

Please consider this suggestion:
Add an option in preferences that does the ff:
*Fix &amp; bug on already downloaded manga.
*Fix import time in obsolete .json files
*Add .nomedia file if it is not present.
*Rename Fakku downloads folder from "Downloads" to "Fakku" for consistency

**Comment by avluis** [comment]
I would like to gather some data in order to address this issue.
Any way you can zip the app's download folder and upload to mega or another host for me to take a look at the file structure.
I will be comparing it with mine to make sure it is consistent before I start work on a routine that will 'cleanup' your downloads.

**Comment by neosubmarino** [comment]
https://drive.google.com/file/d/0B32GQKXQywOYWjludktYN0hxUGs/view?usp=docslist_api

The ff. should be noted:
1. The 'Downloads' folder is fakku downloads.
2. There are content.json and contentV2.json files.
3. I no longer have a sample of the obsolete .json from FakkuDroidV2.
4. There are empty folders named after mangas not included in the zip. This may be due to failed downloads.

Effort vs benefit; I think it's best to just let the obsolete .json files organically go extinct.

**Comment by avluis** [comment]
Thanks, I'll see what sort of balance I can strike while I take a look at those files.
I'll let you know once I start working on this one.

**Comment by neosubmarino** [comment]
None of the files in the zip exhibit the issue described in this ticket. I no longer have a sample of the obsolete .json file and because FakkuDroidV2 no longer works, I also can't reproduce the issue.

As a tester I've come at a dead end.

Only way to see the structure of the old .json file is to reverse engineer the old code. What i do remember is it doesn't have an entry for 'downloadDate' and that's what causes the problem. The old json is kept on import and whatever missing data is generated and kept in appdata.

**Comment by neosubmarino** [comment]
WAIT! I think i found an archived one. Ill upload a sample once it's confirmed.

**Comment by neosubmarino** [comment]
Wait! I got one archived.

https://drive.google.com/open?id=0B32GQKXQywOYN2JPcHlRclBxc1k

**Comment by avluis** [comment]
Awesome - I'll take a look at that one.

**Comment by csaki** [comment]
Please test and if it works, close the issue.

**Comment by avluis** [comment]
Awesome - let me do a re-import.

**Comment by neosubmarino** [comment]
Needs more testing. App now creates a new contentV2.json file containing the import timestamp under 'downloadDate'. Reinstalling the app does not change the import timestamp anymore. Import processing time also significantly increased. I won't be closing this issue for now.

Build details:
version: Hentoid 1.1.1
path: internal updater from 1.1.0, and [here](https://github.com/csaki/Hentoid/releases/download/v1.1.1/hentoid.apk)

@avluis can you upload a copy of the folder where the "downloadDate is 0" issue is happening and link it here.

**Comment by avluis** [comment]
Here is a [zip](https://drive.google.com/open?id=0BycOIcYbBvF_bFJ1MFMySk80Wkk) with the requested data.
I am using OS X so please inspect the zip file for any Mac resource forks (if testing with the app itself) before importing.

**Comment by neosubmarino** [comment]
Verified fixed. But while testing this we found another bug regarding importing mangas using obsolete .json files.

Closing ticket.
