### ISSUE TITLE
[Bug] Tapping next page button on last page resets scroll position

### ISSUE THREAD

**Issue by neosubmarino** [csaki/Hentoid#12]
Affects version: 1.0.8

Repro steps:
1. Go to downloads UI.
2. Advance to last page with content.
3. Scroll down and take note of scroll position.
4. Tap next page button.
5. Notice current scroll position.

Note: Issue does not occur on first page and previous page button.

**Comment by avluis** [comment]
While I am not sure this can be fixed without rewriting a few functions, this bug report has made me aware of a similar issue.
@csaki I got a PR on the way to improve pagination - but I won't be able to fix this specific bug without your guidance (rewriting the searchContent method to not recreate the view).
But I do have a few performance improvements on the way for folks with bigger lists.

**Comment by csaki** [comment]
Please test and if it works, close the issue.

**Comment by avluis** [comment]
Confirmed fixed by @csaki
