### ISSUE TITLE
[Bug] Invoking "web search" in a webview causes the app to crash.

### ISSUE THREAD

**Issue by neosubmarino** [csaki/Hentoid#14]
In a webview activity, tapping and holding text will show the text selection CAB. In this CAB there is a menu overflow that has a web search option. Selecting this option will cause the app to crash.

Affects version: 1.0.8

Device os: 4.2.2

Frequency: 100%

Repro steps:
1. Launch app and proceed to any webview activity.
2. Tap and hold over text.
3. When the CAB appears, select the overflow menu and tap "web search".

Result: A crash report toast will appear and the app will relaunch.

**Comment by avluis** [comment]
When I tap on this, I'm not getting the crash - I'm on 5.1.1 so it must be a compatibility library issue.

**Comment by avluis** [comment]
I need to create a few more device configurations in order to address this.
Hopefully one will give me this crash.
Do you know how to gather logcat data from your Android device?

**Comment by neosubmarino** [comment]
I know how to with ddms, but im without a pc anytime soon. Ill be looking into a console emulator to do that. Ill get back to you once i have it.

**Comment by neosubmarino** [comment]
Here you go.

https://drive.google.com/folder/d/0B32GQKXQywOYcENEbFZaVmRZNHM/edit

I've added you on google+

**Comment by avluis** [comment]
BAM! Thank you - the crashlog tells me exactly what I need to fix.
Will try and work on this in a few (after I eat, lol).

**Comment by avluis** [comment]
@neosubmarino
Mind trying this [build](https://drive.google.com/open?id=0BycOIcYbBvF_NTBQUGlyM2V5NlE) and seeing if you can reproduce the issue.

You may get a signature invalid message, since I built this and not @csaki - simply uninstall Hentoid (your data will still be there) and try again.

**Comment by neosubmarino** [comment]
Verified fixed. Current long press behavior now highlights a word but does not show CAB.

Issue resolved.

**Comment by avluis** [comment]
What sort of device and Android version do you have, I may have to implement an compatible method to address older devices.
The expected behavior is no highlight at all.

**Comment by neosubmarino** [comment]
Cherry Mobile Flare S
Model: Q360
Manufacturer: Cherry Mobile
OS: AOSP 4.2.2 rooted

The highlight only shows 'while' text is long pressed. Releasing the tap and hold won't leave anything highlighted.

**Comment by avluis** [comment]
Oh! OK - good, that's the behavior I am looking for.
