### ISSUE TITLE
[Bug] Pururin downloads no longer work

### ISSUE THREAD

**Issue by neosubmarino** [csaki/Hentoid#16]
Priority: blocker

Pururin has updated the website and hentoid is now unable to download anything, from any device, using any connection.

This may be due to the page that says "checking your browser"

**Comment by avluis** [comment]
Correct - it seems the download manager is treating it as a new session and so any cookies set by Pururin when first accessed (and when you get the "Checking your browser") is not being respected or ignored.
I don't have much experience working with the download manager in Hentoid so @csaki will have to take a look and see if it is possible to implement a handler for this check.

**Comment by csaki** [comment]
Hi, I found the problem and I think that I fixed it. 
The page "Checking your browser" generate a special cookie, this cookie has to match with your Agent User. And well, I added this line to httpclient:
        urlConnection.setRequestProperty("User-Agent", Constants.USER_AGENT);

And the webview:
        webview.getSettings().setUserAgentString(Constants.USER_AGENT);

I am going to test a little more and I'm going to release the new version.

**Comment by avluis** [comment]
OK, I can confirm from my end that the changes allow the download manager to make use of the cookie set by Pururin - and so, it is able to download once again with no issue.

**Comment by avluis** [comment]
Fixed by @csaki 0282b1fb68660f2138f1c031692a747c2741d65e
