### ISSUE TITLE
Enhance built-in updater

### ISSUE THREAD

**Issue by avluis** [csaki/Hentoid#19]
The current UpdateChecker simply checks if there is a new update available.

I would like to augment this with a built-in updater:
Check for updates on startup (as it currently does).
If an update is available, then it notifies of such (does this as well).
Then offers to download said update in the background.
Once the update is downloaded, options are offered to install the update.

In addition, I am planning to leverage off GitHub and use the current repository to host the update itself.

**Comment by avluis** [comment]
@neosubmarino I need you to test this on your device (I run the latest Android): [Google Drive](https://drive.google.com/open?id=0BycOIcYbBvF_NTBQUGlyM2V5NlE) or
[Test Server](https://avnet.ws/apps/hentoid/updates/app-debug.apk)

I have introduced a built-in app updater #20 
While testing, you will always get the update notification (due to the json file on my server).
This is to allow you to see the feature in action.
I need you to make sure the app runs on your device - finds an available update - offers to download and then install.
If you encounter any issues while doing this, then I would love to get that logcat.

**Comment by neosubmarino** [comment]
On it.

**Comment by avluis** [comment]
I'm going to go ahead and close this one as the updater is working - now I just need to concentrate on #25 & #26
