### ISSUE TITLE
Update notification ticker states "Tap to install the update!" before update is downloaded. 

### ISSUE THREAD

**Issue by neosubmarino** [csaki/Hentoid#26]
When the app checks for updates and an update is available, a notification is delivered. When this notification is delivered, the status bar briefly shows the notification ticker. The ticker states "Tap to install the update!" before the update is downloaded and ready to be installed.

Result: The ticker states that the update is ready to install but the notification states that it is ready for download.

Expected result: The ticker should state that "An update is available!"

Affects version: 1.1.0 all revisions
Affects OS: 4.4.4 and below

Adverse effect: In OS 5.0 and above, the string passed to setTicker() [is used by accessibility services](http://developer.android.com/reference/android/app/Notification.html#tickerText) and may cause confusion.

Screenshots:
![screenshot_2015-08-23-00-45-49](https://cloud.githubusercontent.com/assets/2737347/9424910/d57128b2-4930-11e5-8815-bcaa2b6f9ab6.png)
![screenshot_2015-08-23-00-45-57](https://cloud.githubusercontent.com/assets/2737347/9424913/df747684-4930-11e5-8658-fee5ef6080a6.png)

Possible cause:
https://github.com/csaki/Hentoid/blob/8112c6c6d871f48c86e9a65b49af4b4713f1afcd/app/src/main/java/me/devsaki/hentoid/updater/UpdateCheck.java#L222

**Comment by avluis** [comment]
[hentoid.apk](https://github.com/csaki/Hentoid/releases/latest) has been updated with #27

**Comment by avluis** [comment]
In order to test, you will need to load an older apk (if your current revision is the same as the one here) - grab that from [here](https://drive.google.com/open?id=0BycOIcYbBvF_R1FWSlBWUUFJdVE).

**Comment by neosubmarino** [comment]
Verified fixed. Ticker text now shows "An update is available!". Closing ticket.

Build details:
version: Hentoid 1.1.0
path: https://drive.google.com/folderview?id=0BycOIcYbBvF_R0VodGJqQUZrUXc&usp=sharing&tid=0BycOIcYbBvF_SzIzai1XZVFSYm8

Screenshot:
![screenshot_2015-08-23-17-01-13](https://cloud.githubusercontent.com/assets/2737347/9427606/317a0fa6-49b9-11e5-815a-34eeb87c40e9.png)

**Comment by avluis** [comment]
Thanks!
