### ISSUE TITLE
Looking to improve these areas.

### ISSUE THREAD

**Issue by avluis** [csaki/Hentoid#32]
This serves as a guide for areas that need improvement.

- [x] An about section has been created for the app and a mockup of what it should look like (as to improve its presentation) has been put together. Now it just need to be implemented.

- [x] The updater can handle the updates and take care of the notifications - but the download library that powers it has a few issues with cached data - need to take the time to look into this before adding any other dependant features.

- [x] There is a 'Check for Updates' button in the navigation bar from releases prior to the built-in updater - this should be moved into the preferences screen to clean up the navigation bar while still providing the user a manual way to query for updates.

- [x] While on the topic of update checks - upon the introduction of the built-in updater, Toast messages are no longer used to indicate if an update is available or not - this is now handled by showing notifications in the notification bar instead. But when a user manually checks for an update, no feedback is currently provided - add some sort of feedback to indicate that the app is indeed checking for updates - in this case a simple Toast displaying "Checking for updates" once pressed, then a "No updates available" will work. If an update is available, then the built-in updater will show a notification instead.

- [x] When a download is complete - a notification message is sent to the notification bar.
When multiple downloads complete - multiple notification messages are sent to the notification bar.
This behavior is seen on wearable devices as well if one is paired to the device.
Merging completed notifications will clean up the notification bar and any other devices paired with the smartphone that show notifications.

- [x] ~~While browsing any of the three supported websites - the app provides floating action buttons (FAB) to navigate back to different sections of the app. I would like to hide these action buttons when the on-screen keyboard has been triggered - which usually means that the user is inputting text, which means the FAB are in the way.~~ FABs on the Browser are now small enough to not get in the way.

- [x] When a download is complete, the download list requires a refresh to display the new content: Have the download list automatically refresh once a download is complete.

**Comment by neosubmarino** [comment]
All of this sounds good. But for manual check for updates, I suggest that the app should show a "Checking for updates..." toast to give the user immediate feedback about the task in progress before a result is received.

**Comment by avluis** [comment]
Good suggestion - added.
