### ISSUE TITLE
Native browser instead of webview (Hitomi.la)

### ISSUE THREAD

**Issue by csaki** [csaki/Hentoid#34]
I'm going to start with hitomi.la because it has a very unfriendly web design and its html structure is simpler than Fakku and Pururin.
Phases:
1 .- New html parser methods: Content list, Category lists (tags, artists, series, etc)
2 .- I was thinking to refactor the project structure. I'm going to create an interface than it'll have all logical business (get the html, parse to java object, get image list, etc).
3 .- Well, I was working in the activity (ContentListActivity) a long time ago, so I'm going to retake it.

**Comment by avluis** [comment]
Awesome - looking forward to seeing this.
