### ISSUE TITLE
Links get misaligned with their corresponding favicon when link text overflows due to text wrapping.

### ISSUE THREAD

**Issue by neosubmarino** [csaki/Hentoid#35]
On devices with awkward screen ratios, low dpi, or small resolutions, link texts overflow to a linebreak due to text wrapping. When this happens the text is misaligned from the favicon.

Affects version: 1.1.2

Screenshot:
* unavailable for now.

Possible solutions:
* Provide an alternate layout for smaller dpi
* Add android:gravity="center" to the LinearLayouts holding the favicon-link pairs.

**Comment by avluis** [comment]
I'm about to push out an update - let me know if I am getting closer or if this is fixed.

**Comment by neosubmarino** [comment]
Just an idea, are you using 'sp' to define text sizes? I saw that you're defining alternative icon sizes and it's best to also define textsizes in sp along with that.

**Comment by avluis** [comment]
No - I am using
```
android:textAppearance="?android:attr/textAppearanceLarge"
```
If a layout is breaking due to text size, then I just need to define an alternative layout for that.

**Comment by avluis** [comment]
And fixed with a442680cfe2324cdf8f7b6633d183066bf013f49
