### ISSUE TITLE
Internal updater behavior design.

### ISSUE THREAD

**Issue by neosubmarino** [csaki/Hentoid#36]
This document is a design guideline for the internal update behavior. It's objective is to streamline the current functionality and provide an elegant and uninterrupting user experience.

Due to contextual behaviors, this document will be divided into two major contexts; Automatic updates, and manual checking for updates.

*AUTOMATIC UPDATES*
* On launch, App should automatically check for updates over wi-fi .
* IF enabled in preferences, app should check for updates over mobile data.
* User should not be informed in any way that the app is checking for updates. No toast or notifications.
* IF there is no update available, user should not be informed in any way. No toast or notifications.
* IF there is an update available, user should be informed by showing a system notification.
* Update process flow continues from there.

*MANUAL CHECK FOR UPDATES*
* There should be a "Check for updates" control in preferences UI.
* Manually checking for updates should override the "Updates over mobile data" preference.
* Tapping the item should immediately show "Checking for updates..." toast.
* IF there is no update available, user should be informed with a toast.
* IF there is an update available, user should be informed with a system notification.
* Update process flow continues from there.

**Comment by avluis** [comment]
Update up - please check new behavior.

**Comment by neosubmarino** [comment]
All good. Closing ticket.
