### ISSUE TITLE
webView redesign

### ISSUE THREAD

**Issue by avluis** [csaki/Hentoid#38]
The floating action buttons are a neat idea when the app is making use of a webView to show online content - but they get in the way.
Implementing them following the [material design guidelines](https://www.google.com/design/spec/material-design/introduction.html#introduction-principles) should improve their current look and behavior.

*Note: Any work and research under this issue must be considered a workaround until @csaki implements an alternative layout, as suggested by issue #34 and as suggested from previous releases of the FakkuDroid app.*

### Default
![1 regular loaded](https://cloud.githubusercontent.com/assets/2737347/9511953/df27b728-4cae-11e5-9a4c-c1ef9b7992bc.JPG)
From top left to bottom right:
- Toolbar
  - Up button
  - Refresh button
- Page body
- Disabled  download FAB

### On a manga page
![2 download loaded](https://cloud.githubusercontent.com/assets/2737347/9511977/42935c90-4caf-11e5-9290-1c1d8eb457c8.JPG)
- On valid manga pages, the download FAB enables by animating to an opaque view

### Refreshing
![3 regular download loading](https://cloud.githubusercontent.com/assets/2737347/9511993/6813ef34-4caf-11e5-8224-5b541b8c318f.JPG)
The following behavior applies to all pages that is currently loading:
- The Refresh button is replaced with a Stop button
- A determinate progress bar appears into view underneath the Toolbar
- The Download FAB becomes translucent and disabled.

#### Default
![4 regular scrolled loaded](https://cloud.githubusercontent.com/assets/2737347/9512049/de3331a2-4caf-11e5-8ce1-14be4a329265.JPG)
#### Manga page
![5 download loaded](https://cloud.githubusercontent.com/assets/2737347/9512050/dfbc459a-4caf-11e5-9833-20af03c6a983.JPG)
#### Loading
![6 regular scrolled loading](https://cloud.githubusercontent.com/assets/2737347/9512052/e3a40a44-4caf-11e5-93a6-7deac132e7e8.JPG)

## Behavior:
* The activity is a top level temporary activity that employs an "**Up**" button. Tapping the Up button will simply end the activity. Behavior based on [Android guidelines](http://developer.android.com/design/patterns/navigation.html).
* No navigational back button is employed on screen. The device "**Back**" button will be used to navigate back.
* The **Toolbar** shares space with the page body and does not block the page body.
  * Scrolling downwards will animate **hide** the toolbar upwards.
  * Scrolling upwards on any part of the page body will immediately animate **show** the toolbar downwards, blocking a small part of the page body until the page is completely scrolled up.
* The **Refresh** button will only be available on fully loaded pages.
* The **Stop** button replaces the Refresh button when the page is currently loading.
* The **Progress bar** appears temporarily on loading pages and disappears briefly after. The progress bar is always anchored to top whether the toolbar is shown or not.
* The **Download FAB** is always shown but translucent and disabled on invalid pages; opaque and enabled on valid manga pages. The **only time the FAB is hidden** is when the keyboard has been invoked. The FAB should also follow behavior defined [here](https://www.google.com/design/spec/components/buttons-floating-action-button.html#buttons-floating-action-button-floating-action-button).
* Animations are important in getting the users attention. As stated in the material guidelines, "*Motion provides meaning*".

## Resources:
* [Changing menu items at runtime](http://developer.android.com/guide/topics/ui/menus.html#ChangingTheMenu)
* [FloatingActionButton library](https://github.com/Clans/FloatingActionButton)
* To clarify, the behavior for the FAB and Toolbar is usually called a [Quick Return Pattern](http://lmgtfy.com/?q=Android+Quick+Return+Pattern): from my research, a Quick Return Pattern is not native to webView, and must be implemented.

**Comment by neosubmarino** [comment]
Edited ticket.

**Comment by avluis** [comment]
Edited ticket to include usable resources.

**Comment by neosubmarino** [comment]
Is there anyway we can implement this using the latest design support library? This supports the quick return pattern and has a lighter less customizable FAB. Not to mention snackbars which we might be able to use in the future.

[Android dev blog](http://android-developers.blogspot.com/2015/05/android-design-support-library.html)
[Can I use Android floating action button using Android Official Library?](http://stackoverflow.com/questions/27166546/can-i-use-android-floating-action-button-using-android-official-library)

**Comment by avluis** [comment]
@neosubmarino Hmm, yeah - that was inferred - all of the above can be implemented with the latest design support library, the only issue is the WebView - that needs to be extended since it doesn't have a native listener when scrolling has been engaged.

**Comment by avluis** [comment]
**_Issue update:_**
The application has undergone some major changes that make it outdated.
I will be closing this for now - please reopen if/when the issue is rewritten.
