### ISSUE TITLE
Typing into the search bar and tapping the Search button in the keyboard does not retract the keyboard.

### ISSUE THREAD

**Issue by neosubmarino** [csaki/Hentoid#39]
Repro steps:
1. Proceed to Downloads activity.
2. Type any search term in the toolbar.
3. In the keyboard, tap the search button. Usually indicated as a magnifying glass.

Result: Nothing happens.

Expected result: The keyboard should simply retract because search is initiated as soon as something is entered into the search field.

**Comment by avluis** [comment]
Tested on 5.1.1.
