### ISSUE TITLE
First launch activity still shows Fakku banner

### ISSUE THREAD

**Issue by wightwulf1944** [csaki/Hentoid#40]
On first launch Hentoid asks for the location to save downloads. In this activity there is a banner at the top that says Fakku. This is a remnant of the old FakkuDroid app.

Expected result: The banner should be appropriate for the app that now also supports Pururin and Hitomi. Possibly a banner that represents the three or a general one for Hentoid that shows neither of the three.

Screenshot:
![screenshot_2015-09-03-17-20-28](https://cloud.githubusercontent.com/assets/2737347/9679550/f8d9ef64-5321-11e5-8484-ee7c71bb0384.png)

**Comment by neosubmarino** [comment]
Can we possibly crowdsource this?
