### ISSUE TITLE
Downloads UI toolbar enhancement

### ISSUE THREAD

**Issue by wightwulf1944** [csaki/Hentoid#41]
This document attempts to address issues about the search function in the Downloads UI that are not severe enough to be considered a bug but trivial enough to be considered.

Issues
* Deactivating the SearchView requires two taps of the "x" button.
* Hardware menu button opens Sort menu under any circumstance.
* Sorting is inaccessible once the SearchView is activated.
* Entering search terms with no matching result will show the closest or last matched result instead of a blank result. There are instances when the search function is used to see 'if' the manga is downloaded and in these cases it is necessary to return a blank result.

Screenshot of all the above behavior together:
![screenshot_2015-09-04-16-24-53](https://cloud.githubusercontent.com/assets/2737347/9679644/ea1c02c2-5322-11e5-9faf-2a76856918f9.png)

Resolution:
- [x] The SearchView should have an "Up" button that deactivates the SearchView.
- [x] Add a dedicated sort menu button to the right of the search button.
- [ ] Hardware menu button should dismiss keyboard and open navigation drawer.
- [ ] The results should be blank if the search term does not match any of the downloaded mangas.

References:
- [Creating a SearchView that looks like the material design guidelines](http://stackoverflow.com/questions/27556623/creating-a-searchview-that-looks-like-the-material-design-guidelines) - stackoverflow
![iaus6 1](https://cloud.githubusercontent.com/assets/2737347/9675813/26270ff6-52f5-11e5-9229-21d41708ed9f.png)

- Icons such as a sort icon [here](https://www.google.com/design/icons/) and [here](https://github.com/google/material-design-icons) - android material resources.

**Comment by avluis** [comment]
@wightwulf1944 Any way you can update this issue with the current master in mind?
Also, have you found a way to filter out results if the query does not match any items?
