### ISSUE TITLE
Download button does not show on Fakku anymore

### ISSUE THREAD

**Issue by keithknoxx** [csaki/Hentoid#44]
Unable to download from Fakku anymore :(

**Comment by wightwulf1944** [comment]
Thanks for reporting this man.

**Comment by avluis** [comment]
Tracking this issue down;
Works on pages like [these](https://www.fakku.net/doujinshi/tokumei-no-megami-tachi-english) but not [this one](https://www.fakku.net/doujinshi/honoka-to-icha-love-ecchi-english).

**Comment by avluis** [comment]
Update [released](https://github.com/csaki/Hentoid/releases/tag/v1.1.3) - closing this unless issue still persists.
