### ISSUE TITLE
Testers & programmers needed

### ISSUE THREAD

**Issue by avluis** [csaki/Hentoid#46]
**Edit**: Abandoned

---

I need volunteers!
If you know your way with Java and/or Android, please contact me!
I can get you up to speed with the Android SDK and Android Studio if you need a refresher or don't know where to start - just get over here already~

**Testers:**
- @GlitcherWolf :smile:
- @cukoid :tada: 

**Programmers:**
- @csaki :mag_right:
- @wightwulf1944 :trophy:
- @avluis :ok_hand:

---
**Build notes:**
- In order to get the debug build, follow [this link](https://github.com/csaki/Hentoid/tree/optimize) and tap on the Hentoid logo.
This should throw an apk at you - please let me know if that is not the case.

- I will be making use of proguard from now on so please let me know of any crashes anywhere and see if you can grab the logcat right around the time that happens.

- Please make sure to clear your logs afterwards - start fresh before moving on with further testing.

- When you think you have a show stopping bug or a collection of them to share, message me so I can open an issue dedicated just for testing (don't want multiple issues on a build that is being actively tested).

- Logcat apps:
[CatLog](https://play.google.com/store/apps/details?id=com.nolanlawson.logcat)
[aLogcat](https://play.google.com/store/apps/details?id=org.jtb.alogcat)

---
Collaborators - please keep conversation here to a minimum, this will be used as an announcement post.

**Comment by avluis** [comment]
Build notes for 1.1.4-alpha:

- Hitomi crashes were being caused by the website triggering the cookie retrieval routine, this build should fix that.
- Once a download is completed, if you tap on the notification or tap on the download list icon, your download list should show the latest downloaded item.

**Comment by avluis** [comment]
**Hey there!**

While the current build that I'm about to talk about is still getting its finishing touches, I need to collect a bit of data before I can move forward.

I need to know who is available to run a few builds that I will be providing on their devices.
And just to ease your doubts, it will not eat your data, so no need to worry about that.

If you are available, please reply here with :+1: and the devices that you will be using.
Please specify what version of Android that device is running, if it is rooted, and if your data resides on a removable sd card.
Additionally, please specify if you know how to grab a logcat from your device - if you don't no need to worry, I will get you up to speed.

--
@wightwulf1944 @GlitcherWolf @cukoid

**Comment by GlitcherWolf** [comment]
5.1.1, N910T (Note 4), rooted, data can be on SD card if necessary. If you could get me up to speed on how to get a logcat, that would be nice.

**Comment by avluis** [comment]
What development tools do you have access to?
Android Studio? Eclipse? Other?

As for logcat, if you have any of the two mentioned above, you can grab logcat easily.
If not, an app can take care of this:
[CatLog](https://play.google.com/store/apps/details?id=com.nolanlawson.logcat)
[aLogcat](https://play.google.com/store/apps/details?id=org.jtb.alogcat)

And [these](http://8s.ms/how-to/logcat-for-non-developers) instructions seem clear enough.

**Comment by GlitcherWolf** [comment]
I have access to Visual Studios, Netbeans, and I can grab Eclipse if the other two is not sufficient. An app may offer easier logcats though. Thanks.

**Comment by avluis** [comment]
Good to know.
Have you worked with the IntelliJ IDE by any chance?
Android Studio uses that so if you are familiar with that, then good.

Anyways, I think I have completed most of the prep work needed to get testing started.
In order to get the debug build, follow [this link](https://github.com/csaki/Hentoid/tree/optimize) and tap on the Hentoid logo.
This should throw an apk at you - please let me know if that is not the case.

This build has been set up to continuously throw update notifications whenever the app starts, so run the updater just one time and then ignore after that.

I will be making use of proguard from now on so please let me know of any crashes anywhere and see if you can grab the logcat right around the time that happens.
Once you grab a logcat, go ahead and clear your logs (those apps should let you do that) before continuing on.
When you think you have a show stopping bug or a collection of them to share, message me so I can open an issue dedicated just for testing (don't want multiple issues on a build that is being actively tested).
Other than that, enjoy testing it out.
