### ISSUE TITLE
Purring server down

### ISSUE THREAD

**Issue by GlitcherWolf** [csaki/Hentoid#47]
Is Pururin going to be removed from the app? The forums was going all about how the owner went MIA and the supposed self sufficient server went down.

**Comment by wightwulf1944** [comment]
I honestly don't know what to do with this one. How bout we continue to monitor their forums for now? Any other suggestions?

**Comment by avluis** [comment]
This is a perfect discussion for the [Google+ group](https://plus.google.com/communities/110496467189870321840) - how about we keep these out of the issue tracker.
