### ISSUE TITLE
Downloads sorting does not apply until app is relaunched.

### ISSUE THREAD

**Issue by wightwulf1944** [csaki/Hentoid#49]
Affects version: 1.1.4
Tested on: 4.2.2, 4.4.2

Repro steps:
1. Navigate to downloads.
2. Change sorting by tapping 3-dot or hardware menu key.
3. Observe.
4. Relaunch app.

Note:
* Refreshing the downloads list does not remedy the issue.
* Switching to, and returning from a different activity does not remedy the issue.

**Comment by avluis** [comment]
I want to expand on this - it seems preferences are not being reloaded as they are changed.
If you update the image quality or change sorting as mentioned here, it will not apply until the app is killed.
