### ISSUE TITLE
[Bug] App does not check for connectivity status before checking for updates

### ISSUE THREAD

**Issue by neosubmarino** [csaki/Hentoid#5]
Affects version: 1.0.5

Adverse effect: The user is given an error toast even if the app is operating normally and there is no problem. (see below)

![screenshot_2015-07-05-04-37-24](https://cloud.githubusercontent.com/assets/2737347/8528013/caf42fa0-2442-11e5-86b7-5fc2d96dfaa8.png)

Reference: http://developer.android.com/training/monitoring-device-state/connectivity-monitoring.html

**Comment by neosubmarino** [comment]
The screenshot is from 1.0.2. But the issue happens on the latest version.

**Comment by avluis** [comment]
That shouldn't be a hard one to fix.
@csaki Is probably already on it.

**Comment by csaki** [comment]
The commit resolves the issue. 
Thanks, Luis.
