### ISSUE TITLE
[Bug] Downloads list does not have page limit.

### ISSUE THREAD

**Issue by neosubmarino** [csaki/Hentoid#6]
Going past pages with content shows "your downloads list is empty"

![screenshot_2015-07-07-16-06-14](https://cloud.githubusercontent.com/assets/2737347/8541694/9f6ee610-24c2-11e5-9317-cb98cfc4cfab.png)

**Comment by avluis** [comment]
Oh~ Thanks for reporting this one.
Shouldn't be too hard to address this one as well.

**Comment by csaki** [comment]
Solved
