### ISSUE TITLE
[UX] Unable to zoom in/out in hitomi.la webview

### ISSUE THREAD

**Issue by neosubmarino** [csaki/Hentoid#7]
This isn't a bug, but not being able to zoom in/out in the hitomi.la webview is very difficult especially on devices with small resolution/dpi.

Adding pinch to zoom would be best but after I've done some research it seems it's not that simple. Here are some references;

http://stackoverflow.com/questions/5125851/enable-disable-zoom-in-android-webview

http://www.johntvolk.com/?p=1

**Comment by csaki** [comment]
Fixed
