### ISSUE TITLE
Known nhentai bugs

### ISSUE THREAD

**Issue by wightwulf1944** [csaki/Hentoid#72]
Affects version 1.1.5 master

Fixed:
- [x] mangas that include non-jpg images in it's gallery causes download errors.
- [x] mangas with a siteid ending in '1' causes download errors.
- [x] manga galleries bigger than 200 images may cause an error.
- [x] nhentai cover images occasionally cannot be downloaded.
- [x] Parsing nhentai image galleries can take too long.

**Comment by avluis** [comment]
@csaki @wightwulf1944

**Comment by wightwulf1944** [comment]
They have an API?! Man I wish I knew about that...

**Comment by csaki** [comment]
No, NHentai doesn't have an API (well, I don't know if they have an API).
I saw the javascript of his reader (static.nhentai.net/js/main.82a43f8c3ce0.js) and it reads an json inside in the html code this:

new nhentai.reader({
			media_url: '//i.nhentai.net/',
			current_page: 1,
			gallery: {"upload_date":1452225032,"num_favorites":0,"media_id":"890442","title":{"japanese":"(C87) [\u9b3c\u811a\u5802 (\u30ab\u30e9\u30c6\u30ab\u30fb\u30d0\u30ea\u30e5\u30fc)] \u63d0\u7763\u30c8\u6b66\u8535\u5f10 (\u8266\u968a\u3053\u308c\u304f\u3057\u3087\u3093 -\u8266\u3053\u308c-)","english":"(C87) [Kikyakudou (Karateka Value)] Teitoku to Musashi Ni (Kantai Collection -KanColle-)"},"images":{"cover":{"h":492,"t":"j","w":350},"pages":[{"h":1688,"t":"j","w":1200},{"h":1688,"t":"j","w":1200},{"h":1720,"t":"j","w":1200},{"h":1720,"t":"j","w":1200},{"h":1720,"t":"j","w":1200},{"h":1720,"t":"j","w":1200},{"h":1720,"t":"j","w":1200},{"h":1720,"t":"j","w":1200},{"h":1720,"t":"j","w":1200},{"h":1720,"t":"j","w":1200},{"h":1720,"t":"j","w":1200},{"h":1720,"t":"j","w":1200},{"h":1720,"t":"j","w":1200},{"h":1720,"t":"j","w":1200},{"h":1720,"t":"j","w":1200},{"h":1720,"t":"j","w":1200},{"h":1720,"t":"j","w":1200},{"h":1720,"t":"j","w":1200},{"h":1720,"t":"j","w":1200},{"h":1720,"t":"j","w":1200},{"h":1720,"t":"j","w":1200},{"h":1720,"t":"j","w":1200},{"h":1720,"t":"j","w":1200},{"h":1720,"t":"j","w":1200},{"h":1720,"t":"j","w":1200},{"h":1720,"t":"j","w":1200}],"thumbnail":{"h":352,"t":"j","w":250}},"scanlator":"","tags":[[1841,"parody","kantai collection"],[2937,"tag","big breasts"],[6346,"language","japanese"],[8378,"tag","glasses"],[18704,"artist","karateka value"],[19018,"tag","dark skin"],[26169,"character","musashi"],[26390,"group","kikyakudou"],[26952,"tag","tall girl"],[29224,"tag","impregnation"],[29922,"character","teitoku"],[32341,"tag","shotacon"],[33172,"category","doujinshi"]],"id":153223,"num_pages":26},
		});

If you check the javascript you are going to understand what means each item.

Check this:
view-source:http://nhentai.net/g/153223/1/

**Comment by csaki** [comment]
How can I replicate "nhentai cover images occasionally cannot be downloaded"?

**Comment by avluis** [comment]
@csaki I don't know the reason behind it, entirely, but I have been able to replicate it consistently with my lenovo tab 2 - this device is running Android 4.4.4.
I'm connecting it to my Mac for ADB so give me a sec while I attach the area of interest from the log.

**Comment by wightwulf1944** [comment]
I am able to replicate it on 1 device only out of 8 tested. Running android 4.2.2

The fix is as Luis described.

I don't really know how to consistently reproduce it.
