### ISSUE TITLE
Cancelling a download in progress will leave an empty folder in it's save directory.

### ISSUE THREAD

**Issue by wightwulf1944** [csaki/Hentoid#74]
Affects 1.1.5 master

Steps to reproduce:
1. Start downloading a manga.
2. Go to download manager and tap cancel on the downloading item.
3. Inspect save directory.

**Comment by avluis** [comment]
While researching this, I also noticed that [this](https://github.com/csaki/Hentoid/blob/master/app/src/main/java/me/devsaki/hentoid/adapters/ContentAdapter.java#L238) is not enough to clean out downloaded files.
I already have a fix working, just need to tie it in with this issue as well.
