### ISSUE TITLE
Navigating back in webview requires two taps on some devices

### ISSUE THREAD

**Issue by wightwulf1944** [csaki/Hentoid#76]
Affects version 1.1.3 to 1.1.5 master
Affects OS: 4.4.2
Does not affect OS: 5.1.1

**Comment by avluis** [comment]
Do you have any devices with 4.4.4 - would like to include/exclude accordingly.

**Comment by wightwulf1944** [comment]
Applied general fix that only changes back behavior when the issue manifests.
