### ISSUE TITLE
[Bug] Spam-tapping next page button results in spam-toasts

### ISSUE THREAD

**Issue by neosubmarino** [csaki/Hentoid#8]
Affects version: 1.0.8

Repro steps:
1. Go to downloads  UI.
2. Advance to last page with content.
3. Tap next page button multuple times.
4. Observe toast.

Reference:
http://stackoverflow.com/questions/16621737/toast-messages-being-queued
http://stackoverflow.com/questions/12922516/how-to-prevent-multiple-toast-overlaps
spam toast sounds delicious.

**Comment by avluis** [comment]
This looks simple enough to fix on my own - thank you for the stack links by the way.
I'll try and get a PR before @csaki gets on this (unless he's already on it).

@csaki Dejame tratar de arreglar esta, k?

**Comment by csaki** [comment]
@avluis it's yours. Thanks btw.

**Comment by avluis** [comment]
@neosubmarino I assume the same behavior is there if you spam the previous button as well, right?

**Comment by neosubmarino** [comment]
@avluis Correct. Hopefully the fixes doesn't interfere with issue #9

**Comment by avluis** [comment]
@neosubmarino They won't - already got it fixed. Will be submitting the PR as soon as I address issue https://github.com/csaki/Hentoid/issues/9

**Comment by csaki** [comment]
Fixed by avluis
