### ISSUE TITLE
Launching the About activity causes the app to crash on some devices

### ISSUE THREAD

**Issue by wightwulf1944** [csaki/Hentoid#82]
Affects version 1.1.5r5

Device info:
Samsung Galaxy Young (Y)
Android 4.0.3
230 x 432 ldpi

Steps to repro:
1. Launch app
2. Launch About activity through nav drawer.

Notes:
* Clearing data or reinstalling the app does not resolve the issue.
* The same device updated to android 4.2 does not reproduce the issue.
* No immediate condition pattern for issue reproduction.
* [LOG file](https://github.com/csaki/Hentoid/files/104732/aboutcrash.txt)

**Comment by avluis** [comment]
K - I know what the issue is, just need to find it on code - thanks for the logcat.

**Comment by avluis** [comment]
Commit pushed - @wightwulf1944 care to test it once again.
I need my hands on a small screen device so I don't have to guess these screen dimensions.

**Comment by wightwulf1944** [comment]
Retest:
1.1.5r5 master January 27th 2016, 4:42 am

Device:
Samsung Galaxy Young (Y)
Android 4.0.3 & 4.2
230 x 432 ldpi, 230 x 430 ldpi

All good, no crash.
