### ISSUE TITLE
[Bug] Tapping the previous page button on the first page of the downloads UI shows incorrect toast

### ISSUE THREAD

**Issue by neosubmarino** [csaki/Hentoid#9]
The toast states "this is the last page" which does not fit into the context of pressing the previous page button in the first page.

Affects version: 1.0.8

**Comment by avluis** [comment]
I'll try and get this in the same PR.

@neosubmarino Are you referring to the toast that says "Not previous page." when tapping on the previous page button.

**Comment by neosubmarino** [comment]
@avluis Correct. I'm referring to the "Not previous page." toast.

**Comment by avluis** [comment]
How does "First page - can\'t proceed any further." sound to you?

**Comment by neosubmarino** [comment]
Sounds good. It's concise and I like the suggestion to download more.

**Comment by avluis** [comment]
@neosubmarino Thanks - keep them bug reports coming.
Helps me learn more and keeps @csaki busy ;)

**Comment by csaki** [comment]
Fixed by avluis
