### ISSUE TITLE
Tapping on a cancelled download takes you to a blank webView page

### ISSUE THREAD

**Issue by wightwulf1944** [csaki/Hentoid#99]
Affects version 1.1.6 - current

Repro steps:
1. Start a download
2. Before the download completes cancel it from the Queue activity.
3. Tap the notification that states the download has been cancelled.

Notes:
- Bug confirmed up to 1.1.6 but may also occur on older versions.
- Not device specific
- Logs not relevant

**Comment by wightwulf1944** [comment]
For reference: https://github.com/csaki/Hentoid/pull/94#issuecomment-202147654

**Comment by avluis** [comment]
@wightwulf1944 I had to do a bit of diagnosing on the build bot, but I finally got it working again - it's even exporting builds automatically as they are done - will have to pick somewhere to upload that to.
Anyways, can you check out latest master and see if you can reproduce this issue after this patch.
I have not.
